
### get all products
GET http://localhost:3001/api/products?title=chair&minPrice=1&maxPrice=1000
Authorization: thisisatoken


### get single product by id
GET http://localhost:3000/api/products/1


### create new product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title":"this is a laptop",
    "description" : "about this laptop",
    "price":700
}

### update a product
PUT http://localhost:3000/api/products/2
Content-Type: application/json

{
    "title":"product one updated again"
}

### delete a product
DELETE http://localhost:3000/api/products/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcnR5cGUiOiJhZG1pbiIsImlhdCI6MTc4ODEzNzAxMywiZXhwIjoxNzg4MjIzNDEzfQ.uN-BpiI2I-2Z_na5vS6jQOd9QcR957x1QnxUaCFj5mg